### ISSUE TITLE
运行和打包都失败

### ISSUE THREAD

**Issue by liuzhenghe30265** [martinageradams/vue-cesium-webpack-starter#1]
`PS C:\Users\admin\Desktop\vue-cesium-webpack-starter-master> yarn serve
yarn run v1.22.15
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                                                                                                           1:43:18 ├F10: PM┤
 error  in ./node_modules/cesium/Source/ThirdParty/zip.js

Module parse failed: Unexpected token (6365:57)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|       function getWorker(options = {}) {
>               return new Worker(new URL(workerData.scripts[0], import.meta.url), options);
|       }
|`

**Comment by martinadamsdev** [comment]
Hi @liuzhenghe30265, thanks for your feedback.
- [ ] What system platform?
- [ ] What is the Node version?
- [ ] Can you describe your problem in detail?

**Comment by martinadamsdev** [comment]
@liuzhenghe30265 最近会花时间看一看
